const fs = require("fs")
const path = require("path")
const matter = require("gray-matter")

const CONTENT_DIR = path.join(__dirname, "../content/blog")
const OUTPUT_JS = path.join(__dirname, "../src/Components/Blog/blogPosts.js")
const OUTPUT_SITEMAP = path.join(__dirname, "../public/sitemap.xml")
const SITE_URL = "https://ghoudizakaria.vercel.app"

function parseMarkdownToBlocks(md) {
  const lines = md.split("\n")
  const blocks = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    if (line.startsWith("## ")) {
      blocks.push({ type: "heading", text: line.slice(3).trim() })
      i++
    } else if (line.startsWith("```")) {
      const lang = line.slice(3).trim() || "javascript"
      i++
      const codeLines = []
      while (i < lines.length && !lines[i].startsWith("```")) {
        codeLines.push(lines[i])
        i++
      }
      i++
      blocks.push({ type: "code", language: lang, code: codeLines.join("\n") })
    } else if (line.trim() === "") {
      i++
    } else {
      const paraLines = []
      while (i < lines.length && lines[i].trim() !== "" && !lines[i].startsWith("## ") && !lines[i].startsWith("```")) {
        paraLines.push(lines[i])
        i++
      }
      blocks.push({ type: "paragraph", text: paraLines.join(" ").trim() })
    }
  }
  return blocks
}

function generate() {
  if (!fs.existsSync(CONTENT_DIR)) {
    fs.mkdirSync(CONTENT_DIR, { recursive: true })
  }

  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"))
  const postsMap = {}

  files.forEach((file) => {
    const match = file.match(/^(.+)\.(en|ar)\.md$/)
    if (!match) return
    const [, slug, lang] = match
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf-8")
    const { data, content } = matter(raw)

    if (!postsMap[slug]) {
      postsMap[slug] = { slug, date: data.date, tags: [], title: {}, description: {}, content: {} }
    }
    if (lang === "en" && data.tags) {
      postsMap[slug].tags = data.tags.split(",").map((t) => t.trim())
    }
    if (data.date) postsMap[slug].date = data.date
    postsMap[slug].title[lang] = data.title
    postsMap[slug].description[lang] = data.description
    postsMap[slug].content[lang] = parseMarkdownToBlocks(content.trim())
  })

  const posts = Object.values(postsMap).sort((a, b) => new Date(b.date) - new Date(a.date))

  const jsOutput = `// Auto-generated by scripts/generate-blog.js — do not edit by hand\nexport const blogPosts = ${JSON.stringify(posts, null, 2)};\n`
  fs.writeFileSync(OUTPUT_JS, jsOutput)

  const staticPages = [
    { path: "/", priority: "1.0", freq: "monthly" },
    { path: "/about", priority: "0.8", freq: "monthly" },
    { path: "/projects", priority: "0.8", freq: "monthly" },
    { path: "/contact", priority: "0.5", freq: "yearly" },
    { path: "/blog", priority: "0.8", freq: "weekly" },
  ]

  const urls = [
    ...staticPages.map(
      (p) => `  <url>\n    <loc>${SITE_URL}${p.path}</loc>\n    <changefreq>${p.freq}</changefreq>\n    <priority>${p.priority}</priority>\n  </url>`
    ),
    ...posts.map(
      (p) => `  <url>\n    <loc>${SITE_URL}/blog/${p.slug}</loc>\n    <lastmod>${p.date}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>`
    ),
  ]

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join("\n")}\n</urlset>\n`
  fs.writeFileSync(OUTPUT_SITEMAP, sitemap)

  console.log(`Generated ${posts.length} blog post(s), blogPosts.js and sitemap.xml updated.`)
}

generate()
