// Auto-generated by scripts/generate-blog.js — do not edit by hand
export const blogPosts = [
  {
    "slug": "ai-for-web-developpers",
    "date": "2026-09-15",
    "tags": [
      "AI",
      "Web Development",
      "LLM",
      "Career"
    ],
    "title": {
      "ar": "أشياء يجب أن يتعلمها كل مطور ويب عن الذكاء الاصطناعي",
      "en": "What Every Web Developer Should Learn About AI"
    },
    "description": {
      "ar": "دليل عملي للمطورين حول مهارات وأدوات ومفاهيم الذكاء الاصطناعي التي تهم فعلاً في 2026 — من واجهات برمجة LLM إلى prompt injection.",
      "en": "A practical guide for web developers on the AI skills, tools, and concepts that actually matter in 2026 — from LLM APIs to prompt injection."
    },
    "content": {
      "ar": [
        {
          "type": "image",
          "text": "تطوير الويب والذكاء الاصطناعي",
          "src": "/blog-images/ai-web-dev-hero.svg"
        },
        {
          "type": "heading",
          "text": "علاش هاذي المرحلة مهمة"
        },
        {
          "type": "paragraph",
          "text": "الذكاء الاصطناعي ماعادش تخصص منفصل يخص \"مهندسي الـ ML\" غير. إلا كنت تبني تطبيقات ويب اليوم، راهو من المرجح برشا تخدم مع API متاع AI، ولا مساعد برمجة بالذكاء الاصطناعي، ولا محتوى مولّد بالـ AI فـ خط سير عملك. ما تحتاجش دكتوراه فـ machine learning. تحتاج فهم عملي وواضح لعدد من المفاهيم باش تبني منتجات موثوقة وتتفادى الأخطاء الشائعة."
        },
        {
          "type": "paragraph",
          "text": "هاذي الأشياء اللي تهم فعلاً."
        },
        {
          "type": "heading",
          "text": "1. كيفاش تخدم الـ LLMs، بصفة عامة"
        },
        {
          "type": "paragraph",
          "text": "ما تحتاجش تفهم backpropagation. لازم تفهم أن نموذج اللغة الكبير (LLM) يتنبأ بالكلمة الجاية بناءً على أنماط فـ بيانات التدريب متاعو، ما عندوش ذاكرة حقيقية بين الطلبات إلا كان أنت اللي عطيتو واحدة، ونجم يبان واثق وهو غالط بالكامل. هاذي النقطة الوحيدة — \"الغلط بثقة\"، ولا \"hallucination\" — لازم تأثر على كل قرار تاخدو فـ منتج يستعمل مخرجات AI."
        },
        {
          "type": "heading",
          "text": "2. استدعاء واجهات AI مثل أي API آخر"
        },
        {
          "type": "paragraph",
          "text": "الخدمة مع API متاع مزود AI ما تختلفش جوهرياً عن الخدمة مع أي REST API. تبعث طلب، تاخد رد، وتتعامل مع الأخطاء وrate limits. مثال بسيط:"
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "const response = await fetch(\"https://api.anthropic.com/v1/messages\", {\n  method: \"POST\",\n  headers: {\n    \"Content-Type\": \"application/json\",\n    \"x-api-key\": process.env.API_KEY,\n  },\n  body: JSON.stringify({\n    model: \"claude-sonnet-4-6\",\n    max_tokens: 1000,\n    messages: [{ role: \"user\", content: \"لخص هذا النص: ...\" }],\n  }),\n})\n\nconst data = await response.json()"
        },
        {
          "type": "paragraph",
          "text": "المهم موش الـ syntax — المهم إنك تتعامل مع مخرجات النموذج كنص غير موثوق ومتغير الطول لازمو validation، موش كقيمة مضمونة ومنظمة."
        },
        {
          "type": "image",
          "text": "مخطط تدفق طلب ورد API متاع LLM",
          "src": "/blog-images/llm-api-flow.svg"
        },
        {
          "type": "heading",
          "text": "3. الـ Prompt Engineering مهارة حقيقية تتعلم"
        },
        {
          "type": "paragraph",
          "text": "التعليمات اللي تبعثها للنموذج تهم بقد الكود اللي يستدعي الـ API. كون دقيق، أعطي أمثلة، اطلب فورمات معين للمخرجات، وقسم المهمة الصعيبة لخطوات — كل هاذي تحسن النتائج بصفة ملموسة. ماهيش سحر — قريبة أكثر من كتابة spec مفصل برشا لمطور جديد قرا الأنترنت بالكامل ولكن ما عندوش context على المشروع متاعك بالضبط."
        },
        {
          "type": "heading",
          "text": "4. المخرجات المنظمة والـ Validation"
        },
        {
          "type": "paragraph",
          "text": "عمرك ما تثق فـ LLM باش يرجع JSON صحيح 100% غير لأنك طلبتها بأدب. دايماً اعمل parse بحذر، شيل code fences متاع الماركداون قبل الـ parsing، تأكد من شكل الرد، وحضر مسار بديل إلا فشل."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "function parseModelJSON(text) {\n  const clean = text.replace(/```json|```/g, \"\").trim()\n  try {\n    return JSON.parse(clean)\n  } catch (err) {\n    return null // تعامل مع هذي الحالة بوضوح، ما تخليش التطبيق يكراش\n  }\n}"
        },
        {
          "type": "heading",
          "text": "5. الـ Retrieval-Augmented Generation (RAG)"
        },
        {
          "type": "paragraph",
          "text": "النماذج ما تعرفش بيانات شركتك، ولا الكود متاعك، ولا الأحداث اللي صارت بعد تاريخ التدريب متاعها. الـ RAG هو نمط جلب معلومات ذات صلة — من قاعدة بيانات، بحث vector، مخزن مستندات — وحقنها فـ الـ prompt قبل ما تطلب من النموذج يجاوب. كمطور ويب، رايح تكون أكثر فأكثر الشخص اللي يربط هاذا الـ pipeline: بحث، جلب، حقن، توليد."
        },
        {
          "type": "image",
          "text": "مخطط pipeline متاع RAG",
          "src": "/blog-images/rag-pipeline.svg"
        },
        {
          "type": "heading",
          "text": "6. الـ Embeddings والبحث الـ Vector، بصفة مفاهيمية"
        },
        {
          "type": "paragraph",
          "text": "الـ embedding يحول النص لقائمة أرقام تعبر على المعنى متاعو، بحيث النصوص \"المتشابهة\" تولي قريبة رقمياً من بعضها. ما تحتاجش تنفذ الرياضيات. تحتاج تعرف وقتاش feature معين يحتاج هاذي التقنية — بحث دلالي، توصيات، إزالة التكرار، تجميع — مقابل وقتاش query عادي فـ قاعدة البيانات كافي."
        },
        {
          "type": "heading",
          "text": "7. مساعدو البرمجة بالـ AI أدوات، موش autopilot"
        },
        {
          "type": "paragraph",
          "text": "مساعدين مثل Claude Code، Copilot، ولا Cursor ينجموا فعلاً يسرعوا التطوير، خاصة للـ boilerplate، الـ refactors، والمكتبات اللي ما تعرفهاش. لكن الكود المولّد لازم يتقرا، يتفحص، ويتفهم قبل ما يطلع للإنتاج. تعامل مع كود كتبو AI بنفس الطريقة اللي تتعامل بيها مع pull request من مطور عمرك ما خدمت معاه — مفيد، لكن لازم review."
        },
        {
          "type": "heading",
          "text": "8. الأمان: الـ Prompt Injection ثغرة حقيقية"
        },
        {
          "type": "paragraph",
          "text": "إلا كان التطبيق متاعك يخلي LLM يقرا محتوى غير موثوق (رسالة من مستخدم، صفحة ويب مجروفة، ملف مرفوع) وبعدها يتصرف بناءً عليه ولا يوريه لمستخدمين آخرين، عندك سطح هجوم جديد. تعليمات خبيثة تنجم تتخبى داخل هذا المحتوى وتحاول تسرق سلوك النموذج. تعامل مع أي نص يقراه النموذج من مصدر خارجي بنفس الطريقة اللي تتعامل بيها مع مدخلات مستخدم غير منظفة فـ query متاع SQL."
        },
        {
          "type": "heading",
          "text": "9. التكلفة والـ Latency قرارات منتج"
        },
        {
          "type": "paragraph",
          "text": "كل استدعاء AI يكلف فلوس ويوخذ وقت. feature يستدعي نموذج كبير ثلاث مرات فـ كل تحميل صفحة رايح يحس بطيء ويولي غالي مع الحجم. اتعلم تستعمل نماذج أصغر وأسرع وقتاش المهمة بسيطة، اعمل caching بقوة، واستعمل streaming للردود باش المستخدم ما يبقاش يستنى قدام شاشة فارغة."
        },
        {
          "type": "heading",
          "text": "10. اعرف الحدود، وقولها"
        },
        {
          "type": "paragraph",
          "text": "أثمن حاجة تنجم تبنيها فـ feature يخدم بالـ AI هي الصراحة على حدودو: وري المصادر، نبّه على الإجابات القليلة الثقة، عطي للمستخدم طريقة سهلة يصحح ولا يبلغ عن غلطة. المستخدمين يثقوا فـ منتجات صريحة على عدم اليقين أكثر بكثير من منتجات تتظاهر بالثقة."
        },
        {
          "type": "heading",
          "text": "خاتمة"
        },
        {
          "type": "paragraph",
          "text": "ما تحتاجش توّلي باحث فـ الذكاء الاصطناعي. تحتاج تتعامل مع الـ AI بنفس الطريقة اللي تتعامل بيها مع أي خدمة خارجية أحياناً ما تكونش موثوقة فـ الـ stack متاعك: افهم طرق فشلها، تأكد من مخرجاتها، وصمم منتجك باش ما يهبطش الشي كامل وقتاها تغلط."
        }
      ],
      "en": [
        {
          "type": "image",
          "text": "Web development and artificial intelligence",
          "src": "/blog-images/ai-web-dev-hero.svg"
        },
        {
          "type": "heading",
          "text": "Why this matters now"
        },
        {
          "type": "paragraph",
          "text": "AI is no longer a separate specialty that only \"ML engineers\" deal with. If you build web apps today, you are very likely to touch an AI API, an AI coding assistant, or AI-generated content at some point in your workflow. You do not need a PhD in machine learning. You need a practical, working understanding of a handful of concepts so you can build reliable products and avoid common mistakes."
        },
        {
          "type": "paragraph",
          "text": "Here is what actually matters."
        },
        {
          "type": "heading",
          "text": "1. How LLMs work, at a high level"
        },
        {
          "type": "paragraph",
          "text": "You do not need to understand backpropagation. You do need to understand that a large language model (LLM) predicts the next token based on patterns in its training data, that it has no real memory between requests unless you give it one, and that it can sound confident while being completely wrong. This single fact — confident wrongness, also called \"hallucination\" — should shape every product decision you make involving AI output."
        },
        {
          "type": "heading",
          "text": "2. Calling AI APIs like any other API"
        },
        {
          "type": "paragraph",
          "text": "Working with an AI provider's API is not fundamentally different from working with any REST API. You send a request, you get a response, you handle errors and rate limits. A simple example:"
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "const response = await fetch(\"https://api.anthropic.com/v1/messages\", {\n  method: \"POST\",\n  headers: {\n    \"Content-Type\": \"application/json\",\n    \"x-api-key\": process.env.API_KEY,\n  },\n  body: JSON.stringify({\n    model: \"claude-sonnet-4-6\",\n    max_tokens: 1000,\n    messages: [{ role: \"user\", content: \"Summarize this text: ...\" }],\n  }),\n})\n\nconst data = await response.json()"
        },
        {
          "type": "paragraph",
          "text": "The important part is not the syntax — it is treating the model output as untrusted, variable-length text that needs validation, not as a guaranteed structured value."
        },
        {
          "type": "image",
          "text": "LLM API request and response flow",
          "src": "/blog-images/llm-api-flow.svg"
        },
        {
          "type": "heading",
          "text": "3. Prompt engineering is a real, learnable skill"
        },
        {
          "type": "paragraph",
          "text": "The instructions you send matter as much as the code that calls the API. Being specific, giving examples, asking for a particular output format, and breaking a complex task into steps all measurably improve results. This is not magic — it is closer to writing a very detailed spec for a junior developer who has read the entire internet but has no context about your specific project."
        },
        {
          "type": "heading",
          "text": "4. Structured output and validation"
        },
        {
          "type": "paragraph",
          "text": "Never trust an LLM to return perfectly formed JSON just because you asked nicely. Always parse defensively, strip markdown code fences before parsing, validate the shape of the response, and have a fallback path for when it fails."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "function parseModelJSON(text) {\n  const clean = text.replace(/```json|```/g, \"\").trim()\n  try {\n    return JSON.parse(clean)\n  } catch (err) {\n    return null // handle this case explicitly, don't crash\n  }\n}"
        },
        {
          "type": "heading",
          "text": "5. Retrieval-Augmented Generation (RAG)"
        },
        {
          "type": "paragraph",
          "text": "Models don't know about your company's data, your codebase, or events after their training cutoff. RAG is the pattern of fetching relevant information — from a database, a vector search, a document store — and inserting it into the prompt before asking the model to answer. As a web developer, you will increasingly be the one wiring this pipeline together: search, retrieve, inject, generate."
        },
        {
          "type": "image",
          "text": "Retrieval-Augmented Generation pipeline",
          "src": "/blog-images/rag-pipeline.svg"
        },
        {
          "type": "heading",
          "text": "6. Embeddings and vector search, conceptually"
        },
        {
          "type": "paragraph",
          "text": "An embedding turns text into a list of numbers that captures its meaning, so that \"similar\" pieces of text end up numerically close to each other. You do not need to implement the math. You do need to know when a feature calls for it — semantic search, recommendation, deduplication, clustering — versus when a normal database query is enough."
        },
        {
          "type": "heading",
          "text": "7. AI coding assistants are tools, not autopilot"
        },
        {
          "type": "paragraph",
          "text": "Assistants like Claude Code, Copilot, or Cursor can genuinely speed up development, especially for boilerplate, refactors, and unfamiliar libraries. But generated code still needs to be read, tested, and understood before it ships. Treat AI-written code the same way you'd treat a pull request from a developer you've never worked with before — useful, but reviewed."
        },
        {
          "type": "heading",
          "text": "8. Security: prompt injection is a real vulnerability"
        },
        {
          "type": "paragraph",
          "text": "If your app lets an LLM read untrusted content (a user message, a scraped webpage, an uploaded file) and then act on it or show its output to other users, you have a new attack surface. Malicious instructions can be hidden inside that content and try to hijack the model's behavior. Treat any text the model reads from an external source the same way you'd treat unsanitized user input in a SQL query."
        },
        {
          "type": "heading",
          "text": "9. Cost and latency are product decisions"
        },
        {
          "type": "paragraph",
          "text": "Every AI call costs money and takes time. A feature that calls a large model three times per page load will feel slow and get expensive at scale. Learn to reach for smaller/faster models when the task is simple, cache aggressively, and stream responses so the user isn't staring at a blank screen."
        },
        {
          "type": "heading",
          "text": "10. Know the limits, and say so"
        },
        {
          "type": "paragraph",
          "text": "The most valuable thing you can build into an AI-powered feature is honesty about its limits: showing sources, flagging low-confidence answers, giving users an easy way to correct or report mistakes. Users trust products that are upfront about uncertainty far more than products that fake confidence."
        },
        {
          "type": "heading",
          "text": "Closing thought"
        },
        {
          "type": "paragraph",
          "text": "You don't need to become an AI researcher. You need to treat AI the way you already treat any other external, occasionally-unreliable service in your stack: understand its failure modes, validate its output, and design your product so that when it's wrong, nothing breaks."
        }
      ]
    }
  },
  {
    "slug": "express-js-cheat-sheet",
    "date": "2026-07-20",
    "tags": [
      "ExpressJS",
      "NodeJS",
      "REST API"
    ],
    "title": {
      "ar": "دليل Express.js الأساسي",
      "en": "Essential Express.js Cheat Sheet"
    },
    "description": {
      "ar": "دليل عملي لبناء REST APIs باستخدام Express.js — يغطي الإعداد، الكائنات الأساسية، الـ middleware، والـ routing.",
      "en": "A practical guide to building REST APIs with Express.js — covering setup, core objects, middleware, and routing."
    },
    "content": {
      "ar": [
        {
          "type": "paragraph",
          "text": "سواء كنت مبتدئ أو تحتاج مراجعة سريعة، هذا الدليل يغطي المفاهيم الأساسية لبناء REST APIs باستخدام Express. مرجع ممتاز تحتفظ بيه لمشروع Node.js الجاي."
        },
        {
          "type": "heading",
          "text": "ما هو Express.js؟"
        },
        {
          "type": "paragraph",
          "text": "Express هو إطار عمل سريع وغير متشدد لـ Node.js. بسيط لكن قوي، مبني على الـ middleware (كل شيء هو دالة في دورة الطلب → الاستجابة)، ومثالي لبناء REST APIs وتطبيقات كاملة."
        },
        {
          "type": "paragraph",
          "text": "الإصدار الخامس من Express يضيف دعم async/await مباشرة في الـ middleware والـ routes، مما يسهل التعامل مع الأخطاء في الكود غير المتزامن."
        },
        {
          "type": "heading",
          "text": "التثبيت والإعداد"
        },
        {
          "type": "code",
          "language": "bash",
          "code": "npm init -y\nnpm install express@5"
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "// server.js\nimport express from \"express\";\nconst app = express();\n\napp.get(\"/\", (req, res) => {\n  res.send(\"Hello Express v5\");\n});\n\napp.listen(3000, () => console.log(\"Server running on 3000\"));"
        },
        {
          "type": "heading",
          "text": "الكائن الأساسي – app"
        },
        {
          "type": "paragraph",
          "text": "app هو تطبيق Express الرئيسي تاعك. هنا تربط الـ middleware وتعرف الـ routes."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.use(middleware);        // ربط middleware\napp.get(\"/\", handler);      // معالجة GET\napp.set(\"view engine\", \"ejs\"); // إعدادات\napp.listen(3000);           // تشغيل السيرفر"
        },
        {
          "type": "heading",
          "text": "الكائن الأساسي – req (الطلب)"
        },
        {
          "type": "paragraph",
          "text": "الكائن req يمثل الطلب الوارد من العميل. هنا تلقى كل شيء يرسله المستخدم للسيرفر."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.get(\"/user/:id\", (req, res) => {\n  console.log(req.params.id);   // معامل URL\n  console.log(req.query.q);     // query string\n  console.log(req.headers);     // الترويسات\n});"
        },
        {
          "type": "heading",
          "text": "الكائن الأساسي – res (الاستجابة)"
        },
        {
          "type": "paragraph",
          "text": "الكائن res هو كيفاش السيرفر يرد على العميل. تنجم ترسل نص، JSON، ملفات، أو حتى تحول المستخدم لصفحة أخرى."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "res.send(\"Hello\");             // نص/HTML\nres.json({ ok: true });        // JSON\nres.status(404).send(\"Not Found\");\nres.redirect(\"/login\");"
        },
        {
          "type": "heading",
          "text": "أساسيات الـ Middleware"
        },
        {
          "type": "paragraph",
          "text": "الـ middleware هي سلسلة الدوال التي يمر بيها الطلب قبل ما يتبعث الرد. تقعد بين الطلب والاستجابة."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "// middleware مدمج\napp.use(express.json());          // قراءة JSON body\napp.use(express.static(\"public\")); // خدمة الملفات الثابتة\n\n// middleware مخصص\napp.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next(); // مرر للدالة التالية\n});"
        },
        {
          "type": "paragraph",
          "text": "كل دالة middleware عندها access لـ req وres وnext — استدعاء next() يمرر التحكم للدالة التالية في السلسلة. إذا نسيتها، الطلب يقعد معلق للأبد."
        },
        {
          "type": "heading",
          "text": "Middleware من أطراف ثالثة"
        },
        {
          "type": "paragraph",
          "text": "توجد منظومة كاملة من الـ middleware تنجم تستعملها: express.json() لقراءة JSON، express.urlencoded() لقراءة الفورمات، helmet لترويسات الأمان، morgan للتسجيل، وcors لطلبات cross-origin."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "import morgan from \"morgan\";\nimport helmet from \"helmet\";\nimport cors from \"cors\";\n\napp.use(morgan(\"dev\"));\napp.use(helmet());\napp.use(cors());"
        },
        {
          "type": "paragraph",
          "text": "دمج هذوما يعطيك قاعدة جاهزة للإنتاج: تسجيل الطلبات، ترويسات أمان معقولة، وتحكم في الوصول من مصادر مختلفة، كل هذا في ثلاثة أسطر."
        },
        {
          "type": "heading",
          "text": "أساسيات الـ Routing"
        },
        {
          "type": "paragraph",
          "text": "الـ routing هو كيفاش تطبيقك يقرر شنوة يدير وقت ما طلب يوصل لـ URL معين. تقول لـ Express: \"إذا شخص زار هذا المسار بهذه الطريقة HTTP، شغل هذه الدالة.\""
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.get(\"/\", (req, res) => res.send(\"GET Home\"));\napp.post(\"/data\", (req, res) => res.json(req.body));\napp.put(\"/user/:id\", (req, res) =>\n  res.send(\"Updated \" + req.params.id));\napp.delete(\"/user/:id\", (req, res) =>\n  res.send(\"Deleted \" + req.params.id));"
        },
        {
          "type": "paragraph",
          "text": "معًا، GET وPOST وPUT وDELETE تتطابق بشكل طبيعي مع العمليات الأربعة الأساسية لـ REST API: القراءة، الإنشاء، التحديث، والحذف."
        },
        {
          "type": "heading",
          "text": "خلاصة"
        },
        {
          "type": "paragraph",
          "text": "هذا هو جوهر Express باختصار: كائن app لإعداد السيرفر، req/res للتواصل مع العملاء، middleware لمعالجة الطلبات في سلسلة، وrouting لتحديد شنوة يتشغل وين. احتفظ بهذا الدليل لمشروع Node.js الجاي."
        }
      ],
      "en": [
        {
          "type": "paragraph",
          "text": "Whether you're a beginner or looking for a quick refresher, this guide covers the core concepts of building REST APIs with Express. A great resource to keep handy for your next Node.js project."
        },
        {
          "type": "heading",
          "text": "What is Express.js?"
        },
        {
          "type": "paragraph",
          "text": "Express is a fast, unopinionated web framework for Node.js. It's minimal but powerful, middleware-based (everything is a function in the request → response cycle), and perfect for building REST APIs and full apps."
        },
        {
          "type": "paragraph",
          "text": "Express v5 introduces async/await support directly in middleware and routes, making error handling in asynchronous code much cleaner."
        },
        {
          "type": "heading",
          "text": "Install & Setup"
        },
        {
          "type": "code",
          "language": "bash",
          "code": "npm init -y\nnpm install express@5"
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "// server.js\nimport express from \"express\";\nconst app = express();\n\napp.get(\"/\", (req, res) => {\n  res.send(\"Hello Express v5\");\n});\n\napp.listen(3000, () => console.log(\"Server running on 3000\"));"
        },
        {
          "type": "heading",
          "text": "Core Object – app"
        },
        {
          "type": "paragraph",
          "text": "app is your main Express application. It's where you plug in middleware and define routes."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.use(middleware);        // Mount middleware\napp.get(\"/\", handler);      // Handle GET\napp.set(\"view engine\", \"ejs\"); // Config\napp.listen(3000);           // Start server"
        },
        {
          "type": "heading",
          "text": "Core Object – req (Request)"
        },
        {
          "type": "paragraph",
          "text": "The req object represents the incoming request from the client. This is where you'll find everything the user is sending to your server."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.get(\"/user/:id\", (req, res) => {\n  console.log(req.params.id);   // URL param\n  console.log(req.query.q);     // Query string\n  console.log(req.headers);     // Headers\n});"
        },
        {
          "type": "heading",
          "text": "Core Object – res (Response)"
        },
        {
          "type": "paragraph",
          "text": "The res object is how your server talks back to the client. You can send text, JSON, files, or even redirect users."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "res.send(\"Hello\");             // Text/HTML\nres.json({ ok: true });        // JSON\nres.status(404).send(\"Not Found\");\nres.redirect(\"/login\");"
        },
        {
          "type": "heading",
          "text": "Middleware Basics"
        },
        {
          "type": "paragraph",
          "text": "Middleware is the chain of functions that a request goes through before a response is sent. It sits between request and response."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "// Built-in middleware\napp.use(express.json());          // Parse JSON body\napp.use(express.static(\"public\")); // Serve static files\n\n// Custom middleware\napp.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next(); // pass to next handler\n});"
        },
        {
          "type": "paragraph",
          "text": "Every middleware function has access to req, res, and next — calling next() passes control to the next function in the chain. Forget it, and the request hangs forever."
        },
        {
          "type": "heading",
          "text": "Third-Party Middleware"
        },
        {
          "type": "paragraph",
          "text": "There's a whole ecosystem of middleware you can plug in: express.json() to parse JSON, express.urlencoded() to parse forms, helmet for security headers, morgan for logging, and cors for cross-origin requests."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "import morgan from \"morgan\";\nimport helmet from \"helmet\";\nimport cors from \"cors\";\n\napp.use(morgan(\"dev\"));\napp.use(helmet());\napp.use(cors());"
        },
        {
          "type": "paragraph",
          "text": "Combining these gives you a production-ready baseline: request logging, sane security headers, and controlled cross-origin access, all in three lines."
        },
        {
          "type": "heading",
          "text": "Routing Basics"
        },
        {
          "type": "paragraph",
          "text": "Routing is basically how your app decides what to do when a request hits a certain URL. You tell Express: \"If someone visits this path with this HTTP method, run this function.\""
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "app.get(\"/\", (req, res) => res.send(\"GET Home\"));\napp.post(\"/data\", (req, res) => res.json(req.body));\napp.put(\"/user/:id\", (req, res) =>\n  res.send(\"Updated \" + req.params.id));\napp.delete(\"/user/:id\", (req, res) =>\n  res.send(\"Deleted \" + req.params.id));"
        },
        {
          "type": "paragraph",
          "text": "Together, GET, POST, PUT, and DELETE map naturally onto the four basic operations of a REST API: read, create, update, and delete."
        },
        {
          "type": "heading",
          "text": "Wrapping Up"
        },
        {
          "type": "paragraph",
          "text": "That's the core of Express in a nutshell: an app object to configure your server, req/res to talk to clients, middleware to process requests in a chain, and routing to decide what runs where. Keep this cheat sheet handy for your next Node.js project."
        }
      ]
    }
  },
  {
    "slug": "race-condition-store-creation",
    "date": "2026-07-15",
    "tags": [
      "Supabase",
      "React Native",
      "Async"
    ],
    "title": {
      "ar": "إصلاح مشكل Race Condition عند إنشاء المتجر مع Supabase",
      "en": "Fixing a Race Condition in Store Creation with Supabase"
    },
    "description": {
      "ar": "كيف اكتشفت وصلحت خطأ متقطع في عملية إنشاء المتجر في HiSabi، والحل اللي خلص المشكل نهائيًا.",
      "en": "How I found and fixed an intermittent bug in HiSabi's store creation flow, and the retry pattern that solved it for good."
    },
    "content": {
      "ar": [
        {
          "type": "heading",
          "text": "السياق"
        },
        {
          "type": "paragraph",
          "text": "أثناء بنائي لـ HiSabi، تطبيق نقطة بيع متعدد المتاجر لمحلات التجزئة، صادفت خطأ متقطع في عملية إنشاء المتجر. أحيانًا، لما صاحب متجر جديد يسجل، التطبيق يعطي خطأ أو يبقى المستخدم في حالة غير مكتملة، لكن مش دايمًا. مشاكل الـ Race Condition محبطة بالضبط لهذا السبب: ما تفشلش في كل مرة."
        },
        {
          "type": "heading",
          "text": "المشكل"
        },
        {
          "type": "paragraph",
          "text": "عملية إنشاء المتجر كانت فيها عدة خطوات غير متزامنة: إنشاء حساب Supabase Auth، إنشاء سجل المتجر، وبعدين ربطهم. مع اتصال شبكة أبطأ شوية، التطبيق كان يحاول يقرا سجل المتجر قبل ما يخلص كتابته فعليًا. النتيجة: قيمة فارغة أو كائن غير مكتمل يستعمل في الخطوات التالية."
        },
        {
          "type": "heading",
          "text": "أول حل جربته وليش ما خدمش"
        },
        {
          "type": "paragraph",
          "text": "أول حاجة فكرت فيها كانت إضافة تأخير ثابت قبل قراءة بيانات المتجر. هذا صلح المشكل في الاختبار، لكنه حل هش، بس يخلي المشكل أقل احتمالًا، مش مستحيل. مع اتصال أبطأ، نفس المشكل يرجع يبان. إذا كنت جديد في البرمجة غير المتزامنة، هذا الفخ اللي لازم تتجنبه: ما تفترضش أبدًا كم من وقت راح تاخذ عملية معينة."
        },
        {
          "type": "heading",
          "text": "الحل الحقيقي"
        },
        {
          "type": "paragraph",
          "text": "بدل ما نخمن مدة التأخير، بنيت حلقة إعادة محاولة بتأخير متزايد: بعد إنشاء المتجر، التطبيق يحاول يجيبه. إذا فشلت المحاولة لأن السجل مازال ما توصلش، ينتظر شوية ويحاول من جديد، لحد عدد محاولات محدد."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "async function fetchStoreWithRetry(storeId, maxAttempts = 5) {\n  for (let attempt = 1; attempt <= maxAttempts; attempt++) {\n    const { data, error } = await supabase\n      .from(\"stores\")\n      .select(\"*\")\n      .eq(\"id\", storeId)\n      .single();\n\n    if (data) return data;\n\n    if (attempt === maxAttempts) throw error;\n\n    await new Promise((resolve) =>\n      setTimeout(resolve, attempt * 300)\n    );\n  }\n}"
        },
        {
          "type": "heading",
          "text": "ليش يخدم"
        },
        {
          "type": "paragraph",
          "text": "هذي الطريقة ما تفترضش كم من وقت راح تاخذ عملية الكتابة في قاعدة البيانات، هي تتفاعل مع الحالة الحقيقية للنظام. مع اتصال سريع، تنجح من المحاولة الأولى بلا أي تأخير محسوس. مع اتصال أبطأ، تعاود المحاولة تلقائيًا بلا ما تفشل عملية التسجيل كاملة."
        },
        {
          "type": "heading",
          "text": "إذا كنت مبتدئ"
        },
        {
          "type": "paragraph",
          "text": "الدرس الأساسي هنا مش خاص بـ Supabase بس: كل مرة تكتب بيانات وبعدين تحتاج تقراها فورًا، ما تثقش في تأخير ثابت. تأكد من النجاح وأعد المحاولة إذا احتجت. هذا النمط الوحيد راح يوفرلك فئة كاملة من الأخطاء اللي تبان أحيانًا بس، وهاذوما أصعب نوع أخطاء تصلحه."
        }
      ],
      "en": [
        {
          "type": "heading",
          "text": "The Context"
        },
        {
          "type": "paragraph",
          "text": "While building HiSabi, a multi-tenant POS app for retail shops, I ran into an intermittent bug during the store creation flow. Occasionally, when a new owner signed up, the app would throw an error or leave the user in a broken state, but only sometimes. Race conditions are frustrating exactly because of that: they don't fail every time."
        },
        {
          "type": "heading",
          "text": "The Problem"
        },
        {
          "type": "paragraph",
          "text": "Store creation involved multiple async steps: creating the Supabase Auth user, creating the store record, then linking them. Under a slightly slower network response, the app would try to read the store record before it had actually finished being written. The result was a null reference or an incomplete object used downstream."
        },
        {
          "type": "heading",
          "text": "What I Tried First and Why It Failed"
        },
        {
          "type": "paragraph",
          "text": "My first instinct was to add a fixed delay before reading the store data. This fixed it in testing, but it is a fragile solution, it just makes the bug less likely, not impossible. On a slower connection, the same problem would resurface. If you are new to async programming, this is the trap to avoid: never assume how long something will take."
        },
        {
          "type": "heading",
          "text": "The Actual Fix"
        },
        {
          "type": "paragraph",
          "text": "Instead of guessing a delay, I built a retry loop with exponential backoff: after creating the store, the app tries to fetch it. If the fetch fails because the record is not available yet, it waits briefly and tries again, up to a fixed number of attempts."
        },
        {
          "type": "code",
          "language": "javascript",
          "code": "async function fetchStoreWithRetry(storeId, maxAttempts = 5) {\n  for (let attempt = 1; attempt <= maxAttempts; attempt++) {\n    const { data, error } = await supabase\n      .from(\"stores\")\n      .select(\"*\")\n      .eq(\"id\", storeId)\n      .single();\n\n    if (data) return data;\n\n    if (attempt === maxAttempts) throw error;\n\n    await new Promise((resolve) =>\n      setTimeout(resolve, attempt * 300)\n    );\n  }\n}"
        },
        {
          "type": "heading",
          "text": "Why It Works"
        },
        {
          "type": "paragraph",
          "text": "This approach doesn't assume how long the database write will take, it reacts to the actual state of the system. On a fast connection, it succeeds on the first attempt with no perceptible lag. On a slower one, it retries automatically without failing the whole signup flow."
        },
        {
          "type": "heading",
          "text": "If You Are Just Starting Out"
        },
        {
          "type": "paragraph",
          "text": "The core lesson here isn't specific to Supabase: whenever you write data and then immediately need to read it back, don't trust a fixed delay. Check for success and retry if needed. This single pattern will save you from a whole category of bugs that only show up sometimes, which are the hardest kind to debug."
        }
      ]
    }
  }
];
